### ISSUE TITLE
"command not found" error while installing without sudo

### ISSUE THREAD

**Issue by badarsh2** [lakshmanaram/Incor#3]
"command not found" error while installing without sudo
![screenshot from 2016-07-08 10-21-21](https://cloud.githubusercontent.com/assets/10472699/16677674/c22ed81e-44f5-11e6-8e1e-b8f594e36e6f.png)

**Comment by lakshmanaram** [comment]
As given in the pypi docs " Packages and scripts installed with 'sudo' will be placed in a operating system specific location" and hence without sudo, it doesn't get recognized. Updated docs of Incor to add sudo. 

Making sudo compulsory while installation needs to be done
